flight_graph = {
    'Albania': set(['United Kingdom']),
    'Algeria': set(['United Kingdom']),
    'Angola': set(['United Kingdom']),
    'Antigua and Barbuda': set(['United Kingdom','Dominican Republic','Saint Kitts and Nevis','Trinidad and Tobago']),
    'Argentina': set(['United Kingdom']),
    'Australia': set(['Australia','Hong Kong','Singapore']),
    'Austria': set(['United Kingdom']),
    'Azerbaijan': set(['United Kingdom']),
    'Bahamas': set(['Cayman Islands','United Kingdom','Turks and Caicos Islands']),
    'Bahrain': set(['Qatar','United Kingdom']),
    'Barbados': set(['United Kingdom']),
    'Belgium': set(['Denmark','United Kingdom']),
    'Bermuda': set(['United Kingdom']),
    'Brazil': set(['United Kingdom']),
    'Bulgaria': set(['United Kingdom']),
    'Canada': set(['United Kingdom']),
    'Cayman Islands': set(['Bahamas']),
    'China': set(['United Kingdom']),
    'Costa Rica': set(['United States']),
    'Croatia': set(['United Kingdom']),
    'Cyprus': set(['United Kingdom']),
    'Czech Republic': set(['United Kingdom']),
    'Denmark': set(['Denmark','Norway','Sweden','Belgium','Germany','United Kingdom','Switzerland']),
    'Dominican Republic': set(['Antigua and Barbuda']),
    'Egypt': set(['United Kingdom']),
    'El Salvador': set(['Spain']),
    'Finland': set(['United States','United Kingdom','Lithuania','Poland']),
    'France': set(['United Kingdom','United States']),
    'Germany': set(['Germany','Denmark','United Kingdom','United States']),
    'Ghana': set(['United Kingdom']),
    'Gibraltar': set(['United Kingdom']),
    'Greece': set(['United Kingdom']),
    'Grenada': set(['Saint Lucia']),
    'Guatemala': set(['El Salvador']),
    'Hong Kong': set(['Australia','United Kingdom']),
    'Hungary': set(['United Kingdom']),
    'India': set(['United Kingdom']),
    'Ireland': set(['United States','United Kingdom']),
    'Isle of Man': set(['United Kingdom']),
    'Israel': set(['United Kingdom']),
    'Italy': set(['United Kingdom','United States']),
    'Jamaica': set(['United Kingdom']),
    'Japan': set(['United Kingdom']),
    'Jersey': set(['United Kingdom']),
    'Jordan': set(['United Kingdom']),
    'Kazakhstan': set(['United Kingdom']),
    'Kenya': set(['United Kingdom']),
    'Kuwait': set(['United Kingdom']),
    'Lebanon': set(['United Kingdom']),
    'Liberia': set(['Sierra Leone']),
    'Libya': set(['United Kingdom']),
    'Lithuania': set(['Finland']),
    'Luxembourg': set(['United Kingdom']),
    'Maldives': set(['Sri Lanka','United Kingdom']),
    'Malta': set(['United Kingdom']),
    'Mauritius': set(['South Africa','United Kingdom']),
    'Mexico': set(['United Kingdom','United States']),
    'Morocco': set(['United Kingdom']),
    'Namibia': set(['South Africa']),
    'Netherlands': set(['United Kingdom']),
    'Nigeria': set(['United Kingdom']),
    'Norway': set(['Denmark','United Kingdom']),
    'Oman': set(['United Arab Emirates']),
    'Poland': set(['Finland','United Kingdom']),
    'Portugal': set(['United Kingdom']),
    'Qatar': set(['Bahrain']),
    'Romania': set(['United Kingdom']),
    'Russia': set(['United Kingdom']),
    'Saint Kitts and Nevis': set(['Antigua and Barbuda']),
    'Saint Lucia': set(['Grenada','United Kingdom','Trinidad and Tobago']),
    'Saudi Arabia': set(['United Kingdom']),
    'Sierra Leone': set(['United Kingdom','Liberia']),
    'Singapore': set(['United Kingdom','Australia']),
    'South Africa': set(['South Africa','United Kingdom','Zimbabwe','Zambia','Mauritius','Namibia']),
    'South Korea': set(['United Kingdom']),
    'Spain': set(['United Kingdom','United States']),
    'Sri Lanka': set(['Maldives']),
    'Sweden': set(['United Kingdom','Denmark']),
    'Switzerland': set(['United Kingdom','Denmark']),
    'Thailand': set(['Thailand','United Kingdom']),
    'Trinidad and Tobago': set(['Saint Lucia','Antigua and Barbuda']),
    'Turkey': set(['United Kingdom']),
    'Turks and Caicos Islands': set(['Bahamas']),
    'Uganda': set(['United Kingdom']),
    'Ukraine': set(['United Kingdom']),
    'United Arab Emirates': set(['United Kingdom','Oman']),
    'United Kingdom': set(['United Kingdom','Spain','Netherlands','Sweden','Denmark','Germany','Italy','Isle of Man','France','Switzerland','Algeria','Antigua and Barbuda','Bermuda','Barbados','Mexico','Croatia','Portugal','Jersey','Jamaica','United States','Cyprus','Malta','Maldives','Mauritius','Morocco','Greece','Austria','Albania','Saint Lucia','Nigeria','Ghana','Kazakhstan','Jordan','United Arab Emirates','Bahrain','Lebanon','Norway','Thailand','India','Belgium','Hungary','Egypt','South Africa','China','Russia','Ireland','Uganda','Argentina','Sierra Leone','Gibraltar','Brazil','Azerbaijan','Finland','Hong Kong','Japan','South Korea','Turkey','Saudi Arabia','Ukraine','Kuwait','Angola','Luxembourg','Bahamas','Kenya','Romania','Czech Republic','Singapore','Bulgaria','Libya','Israel','Poland','Canada']),
    'United States': set(['United States','United Kingdom','Spain','France','Germany','Mexico','Ireland','Italy','Finland','Virgin Islands']),
    'Virgin Islands': set(['United States']),
    'Zambia': set(['South Africa']),
    'Zimbabwe': set(['South Africa'])
}
